import { defineConfig, transformerVariantGroup } from 'unocss';
import presetWind from '@unocss/preset-wind';
import presetTypography from '@unocss/preset-typography';
import presetIcons from '@unocss/preset-icons';

export default defineConfig({
  theme: {
    colors: {
      surface: 'var(--gray-0)',
      muted: 'var(--gray-6)',
      text: 'var(--gray-12)',
      accent: 'var(--brand-7)',
      accentDark: 'var(--brand-9)',
      info: 'var(--cyan-6)',
      success: 'var(--green-6)',
      warn: 'var(--orange-6)',
      danger: 'var(--red-6)',
    },
    boxShadow: {
      card: 'var(--shadow-4)',
    },
    borderRadius: {
      sm: 'var(--radius-2, 5px)',
      md: 'var(--radius-3, 1rem)',
      lg: 'var(--radius-4, 2rem)',
      full: '999px',
    },
    fontFamily: {
      sans: 'Inter, var(--font-neo-grotesque, system-ui), sans-serif',
      heading: 'Nunito, var(--font-neo-grotesque, system-ui), sans-serif',
    },
  },
  shortcuts: [
    [
      'btn-primary',
      'inline-flex items-center justify-center gap-2 rounded-full bg-[var(--brand-6)] px-5 py-2.5 text-[var(--gray-0)] font-medium tracking-tight transition-colors duration-200 ease-in-out hover:bg-[var(--brand-7)] focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-[var(--brand-6)]',
    ],
    [
      'btn-ghost',
      'inline-flex items-center justify-center gap-2 rounded-full border border-[var(--brand-6)] px-5 py-2.5 text-[var(--brand-6)] font-medium tracking-tight transition-colors duration-200 ease-in-out hover:bg-[rgba(14,99,91,0.12)] focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-[var(--brand-6)]',
    ],
    ['btn-sm', 'px-4 py-2 text-sm'],
    ['button', 'btn-primary'],
    ['button--ghost', 'btn-ghost'],
    ['button--sm', 'btn-sm'],
    ['btn-row', 'flex flex-wrap items-center gap-4 mt-6'],
    ['section-shell', 'mx-auto my-[clamp(2rem,6vw,6rem)] w-full max-w-[min(var(--size-2xl,80rem),82rem)]'],
    ['section-narrow', 'max-w-[840px]'],
    ['section-title', 'text-[clamp(1.8rem,4vw,3rem)] font-bold mb-4'],
    ['section-subtitle', 'text-[clamp(1rem,2vw,1.25rem)] text-[var(--gray-6)] mt-2'],
    ['section__title', 'section-title'],
    ['section__subtitle', 'section-subtitle'],
    ['hero-badge', 'inline-flex items-center gap-2 rounded-full border border-[var(--brand-6)] bg-[var(--gray-0)] text-[var(--brand-7)] px-[0.9rem] py-[0.35rem] text-[0.85rem] font-semibold tracking-[0.08em] uppercase'],
    ['cta-primary', 'btn-primary nav-button inline-flex justify-center'],
    ['hero-headline', 'text-[clamp(2rem,4vw,3rem)] font-bold leading-[1.1] my-[clamp(0.4rem,1.5vw,0.8rem)]'],
    ['hero-copy', 'text-[clamp(1rem,2vw,1.15rem)] text-[var(--gray-6)] max-w-[620px]'],
    ['grid-cards', 'grid items-stretch gap-[1.5rem] grid-cols-[repeat(auto-fit,minmax(240px,1fr))]'],
    ['grid-balanced', 'auto-rows-[minmax(0,1fr)]'],
    [
      'card-shell',
      'flex flex-col gap-[1.1rem] rounded-[20px] border border-[rgba(148,163,184,0.22)] bg-[var(--gray-0)] p-[1.75rem] shadow-[0_20px_40px_-32px_rgba(15,23,42,0.6)]',
    ],
    ['card-highlight', 'border-[rgba(14,99,91,0.6)] shadow-[0_22px_42px_-28px_rgba(14,99,91,0.45)]'],
    ['card-title', 'm-0 text-[1.2rem] font-semibold'],
    ['card-copy', 'm-0 text-[var(--gray-6)]'],
    ['card-measurement', 'card-shell rounded-[18px] border-[rgba(148,163,184,0.35)] bg-white gap-[0.9rem]'],
    ['card-teal', 'card-shell rounded-[20px] border-[rgba(14,99,91,0.3)] bg-[rgba(14,99,91,0.1)]'],
    ['card-refine', 'card-shell rounded-[18px] border-[rgba(14,99,91,0.25)] bg-[rgba(14,99,91,0.08)]'],
    ['summary-card', 'grid gap-3 rounded-[18px] border border-[rgba(14,99,91,0.2)] bg-[rgba(14,99,91,0.12)] p-[clamp(1.4rem,3vw,2rem)]'],
    ['grid-stack', 'grid gap-[clamp(1.25rem,3vw,2rem)]'],
    ['list-reset', 'list-none m-0 p-0'],
    ['pill-teal', 'inline-flex items-center gap-2 rounded-full border border-[rgba(14,99,91,0.3)] bg-[rgba(255,255,255,0.85)] px-3 py-1 text-[var(--brand-7)] font-semibold'],
    ['chip-soft', 'inline-flex items-center gap-2 rounded-full bg-[rgba(14,99,91,0.12)] px-3 py-[0.35rem] text-sm font-semibold text-[var(--brand-7)]'],
    ['list-card', 'grid gap-[0.35rem] rounded-[14px] border border-[rgba(148,163,184,0.25)] bg-white px-4 py-3'],
    ['meta-muted', 'flex flex-wrap gap-2 text-xs text-[var(--gray-6)]'],
    ['chip-muted', 'inline-flex items-center gap-1 rounded-full bg-[rgba(14,99,91,0.08)] px-2.5 py-[0.2rem] text-xs font-medium text-[var(--brand-7)]'],
    [
      'intake-shell',
      'mx-auto grid max-w-[1200px] items-start gap-[clamp(1.5rem,4vw,2.5rem)] px-4 py-10 pb-20 md:px-8 lg:grid-cols-[minmax(0,1fr)_minmax(240px,320px)] lg:pb-12',
    ],
    ['intake-flow', 'flex flex-col gap-[clamp(1.5rem,3vw,2.5rem)]'],
    [
      'intake-banner',
      'grid gap-3 rounded-[24px] border border-[rgba(14,99,91,0.18)] bg-[linear-gradient(135deg,rgba(14,99,91,0.12),rgba(99,102,241,0.08))] p-[clamp(1.5rem,4vw,2.5rem)] shadow-[0_24px_48px_-32px_rgba(14,99,91,0.38)]',
    ],
    ['badge-subtle', 'inline-flex items-center gap-2 text-[0.8rem] font-semibold uppercase tracking-[0.12em] text-[var(--brand-7)]'],
    ['badge', 'badge-subtle'],
    [
      'form-card',
      'grid gap-[clamp(1.2rem,3vw,1.75rem)] rounded-[24px] border border-[rgba(148,163,184,0.25)] bg-[var(--gray-0)] p-[clamp(1.75rem,4vw,2.5rem)] shadow-[0_28px_54px_-40px_rgba(15,23,42,0.55)]',
    ],
    ['form-ribbon', 'inline-flex items-center gap-2 rounded-full bg-[rgba(14,99,91,0.12)] px-3 py-[0.4rem] text-[0.8rem] font-semibold uppercase tracking-[0.12em] text-[var(--brand-7)]'],
    ['form-ribbon-muted', 'form-ribbon bg-[rgba(148,163,184,0.18)] text-[rgba(30,41,59,0.72)]'],
    ['field-wrap', 'grid gap-2'],
    ['field-label', 'font-semibold text-[var(--gray-12)]'],
    ['field-hint', 'text-sm text-[var(--gray-6)]'],
    ['input-base', 'w-full rounded-[14px] border border-[rgba(148,163,184,0.45)] bg-white px-3 py-3 text-base'],
    ['input-chip', 'inline-flex items-center rounded-full bg-[rgba(148,163,184,0.18)] px-2 py-[0.2rem] text-xs text-[var(--gray-6)]'],
    ['input-pair', 'grid gap-3'],
    ['input-pair-head', 'flex items-center justify-between gap-2'],
    ['input-pair-controls', 'grid gap-2'],
    ['grid-two', 'grid gap-4 sm:grid-cols-2'],
    ['grid-responsive', 'grid gap-4 md:grid-cols-2'],
    ['past-card', 'grid gap-4 rounded-[16px] border border-[rgba(148,163,184,0.3)] bg-white p-4'],
    ['premium-panel', 'grid gap-4 rounded-[18px] border border-[rgba(14,99,91,0.25)] bg-[rgba(14,99,91,0.08)] p-[clamp(1.1rem,3vw,1.6rem)]'],
    ['premium-actions', 'flex flex-wrap items-center gap-3'],
    ['premium-note', 'text-sm text-[var(--gray-6)]'],
    ['toggle-row', 'flex items-center gap-3 rounded-[16px] border border-[rgba(14,99,91,0.25)] bg-white/80 px-4 py-3'],
    ['sticky-shell', 'fixed left-1/2 bottom-5 z-30 flex -translate-x-1/2 justify-center pointer-events-none'],
    ['sticky-inner', 'pointer-events-auto flex items-center gap-3 rounded-full border border-[rgba(14,99,91,0.25)] bg-[var(--gray-0)] px-6 py-2 shadow-[0_22px_44px_-24px_rgba(14,99,91,0.45)]'],
    ['sticky-label', 'font-semibold text-[var(--gray-12)]'],
    ['intake-banner__label', 'badge-subtle'],
    ['intake-banner__headline', 'hero-headline'],
    ['intake-card', 'form-card'],
    ['intake-card--basics', 'form-card'],
    ['intake-card--measurements', 'form-card'],
    ['intake-card--past', 'form-card'],
    ['intake-card--premium', 'form-card'],
    ['intake-card--submit', 'form-card gap-5'],
    ['intake-card--premium-locked', 'form-card border-dashed border-[rgba(148,163,184,0.4)] bg-[rgba(15,23,42,0.04)]'],
    ['coach-ribbon', 'form-ribbon'],
    ['coach-ribbon--muted', 'form-ribbon bg-[rgba(148,163,184,0.18)] text-[rgba(30,41,59,0.72)]'],
    ['intake-card__header', 'grid gap-2'],
    ['input-grid', 'grid gap-4'],
    ['input-grid--two', 'grid gap-4 sm:grid-cols-2'],
    ['input-grid--pairs', 'grid gap-6 md:grid-cols-2 xl:grid-cols-3'],
    ['field', 'grid gap-2'],
    ['field__label', 'font-semibold text-[var(--gray-12)]'],
    ['field__hint', 'text-sm text-[var(--gray-6)]'],
    ['input-pair', 'grid gap-3'],
    ['input-pair__head', 'flex items-center justify-between gap-2'],
    ['input-pair__chip', 'input-chip'],
    ['input-pair__controls', 'grid gap-2'],
    ['input-row', 'grid gap-4 md:grid-cols-2'],
    ['intake-card__actions', 'flex flex-wrap items-center gap-3'],
    ['intake-card__empty', 'text-sm text-[var(--gray-6)]'],
    ['past-sports__items', 'grid gap-4'],
    ['past-sport-item', 'grid gap-4 rounded-[16px] border border-[rgba(148,163,184,0.3)] bg-white p-4'],
    ['past-sport-flags', 'grid gap-4 md:grid-cols-3'],
    ['past-sport-picker', 'relative'],
    ['premium-actions', 'flex flex-wrap items-center gap-3'],
    ['premium-note', 'text-sm text-[var(--gray-6)]'],
    ['premium-block', 'grid gap-6'],
    ['premium-header', 'grid gap-2'],
    ['premium-toggle', 'toggle-row'],
    ['premium-toggle__copy', 'grid gap-1'],
    ['premium-toggle__title', 'm-0 font-semibold text-[var(--gray-12)]'],
    ['premium-toggle__hint', 'm-0 text-sm text-[var(--gray-6)]'],
    ['premium-header__badge', 'badge-subtle text-[var(--brand-9)]'],
    ['premium-groups', 'grid gap-5'],
    ['premium-group', 'premium-panel'],
    ['premium-group__header', 'flex flex-wrap items-center justify-between gap-3'],
    ['premium-group__items', 'grid gap-4'],
    ['premium-item', 'grid gap-4 md:grid-cols-2 rounded-[14px] border border-[rgba(148,163,184,0.3)] bg-white p-4'],
    ['premium-item__note', 'md:col-span-2'],
    ['premium-empty', 'text-sm text-[var(--gray-6)]'],
    ['premium-lock', 'grid gap-4'],
    ['premium-lock__header', 'flex flex-wrap items-center gap-3'],
    ['premium-lock__icon', 'inline-flex h-10 w-10 items-center justify-center rounded-xl bg-[rgba(14,99,91,0.15)] text-xl'],
    ['premium-lock__title', 'm-0 text-lg font-semibold text-[var(--gray-12)]'],
    ['premium-lock__copy', 'card-copy m-0'],
    ['premium-lock__actions', 'flex flex-wrap items-center gap-3'],
    ['privacy-note', 'm-0 text-sm text-[var(--gray-6)]'],
    ['intake-aside', 'card-shell gap-4 border-[rgba(148,163,184,0.25)] bg-[rgba(15,23,42,0.05)] shadow-[0_18px_36px_-30px_rgba(15,23,42,0.3)]'],
    ['intake-sticky', 'sticky-shell w-[calc(100%-1.5rem)] max-w-[420px] md:w-auto md:max-w-none'],
    ['intake-sticky__inner', 'sticky-inner'],
    ['intake-sticky__label', 'sticky-label'],
    ['page', 'section-shell max-w-[960px] gap-8'],
    ['card', 'card-shell'],
    ['summary-card', 'card-teal'],
    ['summary-grid', 'grid gap-3 sm:grid-cols-2 md:grid-cols-3'],
    ['metric', 'summary-tile'],
    ['metric__label', 'summary-label'],
    ['metric__value', 'summary-value'],
    ['premium-list', 'list-reset grid gap-3'],
    ['actions', 'flex flex-wrap items-center gap-4'],
    ['status-area', 'min-h-[1.6rem]'],
    ['empty-state', 'grid gap-3 justify-items-center rounded-[18px] border border-dashed border-[rgba(148,163,184,0.4)] p-[clamp(1.5rem,3vw,2.25rem)] text-center text-[var(--gray-6)]'],
    ['coach-ribbon--accent', 'form-ribbon text-[var(--brand-9)] bg-[rgba(14,99,91,0.18)]'],
    ['summary-tile', 'grid gap-1 rounded-[18px] border border-[rgba(148,163,184,0.25)] bg-[rgba(241,245,249,0.6)] p-[clamp(1.1rem,3vw,1.6rem)]'],
    ['summary-label', 'block text-sm text-[var(--gray-6)]'],
    ['summary-value', 'block text-base font-semibold text-[var(--gray-12)]'],
    ['match-card', 'grid gap-[0.6rem] rounded-[20px] border border-[rgba(148,163,184,0.25)] bg-[rgba(241,245,249,0.55)] shadow-[0_24px_48px_-38px_rgba(15,23,42,0.35)] p-[clamp(1.2rem,2.6vw,1.7rem)]'],
    ['match-header', 'flex items-center gap-3'],
    ['match-rank', 'inline-flex h-8 w-8 items-center justify-center rounded-full bg-[rgba(14,99,91,0.18)] font-bold text-[var(--brand-7)]'],
    ['match-score', 'ml-auto font-bold text-[1.05rem] text-[var(--brand-7)]'],
    ['card-measurement', 'card-shell rounded-[18px] border-[rgba(148,163,184,0.35)] bg-white gap-[0.9rem]'],
    ['card-teal', 'card-shell rounded-[20px] border-[rgba(14,99,91,0.3)] bg-[rgba(14,99,91,0.1)]'],
    ['card-refine', 'card-shell rounded-[18px] border-[rgba(14,99,91,0.25)] bg-[rgba(14,99,91,0.08)]'],
    ['summary-card', 'grid gap-3 rounded-[18px] border border-[rgba(14,99,91,0.2)] bg-[rgba(14,99,91,0.12)] p-[clamp(1.4rem,3vw,2rem)]'],
    ['grid-stack', 'grid gap-[clamp(1.25rem,3vw,2rem)]'],
    ['list-reset', 'list-none m-0 p-0'],
    ['pill-teal', 'inline-flex items-center gap-2 rounded-full border border-[rgba(14,99,91,0.3)] bg-[rgba(255,255,255,0.85)] px-3 py-1 text-[var(--brand-7)] font-semibold'],
    [
      'image-tile',
      'relative block w-full aspect-square overflow-hidden rounded-[20px] bg-[rgba(15,23,42,0.04)] border border-[rgba(148,163,184,0.18)] shadow-[inset_0_0_0_1px_rgba(255,255,255,0.4)]',
    ],
    ['text-muted', 'text-[var(--gray-6)]'],
    ['card-base', 'rounded-[var(--radius-4)] border border-[var(--gray-3)] bg-[var(--gray-0)] shadow-[var(--shadow-4)]'],
    ['container-page', 'mx-auto w-full max-w-[70rem] px-[clamp(1.5rem,4vw,3rem)]'],
  ],
  presets: [
    presetWind(),
    presetTypography(),
    presetIcons({
      scale: 1.1,
      extraProperties: {
        display: 'inline-block',
        'vertical-align': 'middle',
      },
    }),
  ],
  transformers: [
    transformerVariantGroup(),
  ],
});
