name: Deploy Cloudflare Worker (Sporty)

on:
  push:
    branches: ["test", "main"]

jobs:
  deploy-test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4      
      - name: Deploy to test (sets secrets + deploy)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: test
          wranglerVersion: "4.38.0"
          secrets: |
            RENDER_API_KEY
          command: >
            deploy
            --env test
            --var RENDER_URL:"${{ vars.RENDER_URL }}"
            --var STRIPE_PUBLIC_KEY:"${{ vars.STRIPE_PUBLIC_KEY }}"
            --var SUPABASE_STORAGE_URL:"${{ vars.SUPABASE_STORAGE_URL }}"
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}


  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4      
      - name: Deploy to production (sets secrets + deploy)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: production
          wranglerVersion: "4.38.0"
          secrets: |
            RENDER_API_KEY
          command: >
            deploy
            --env production
            --var RENDER_URL:"${{ vars.RENDER_URL }}"
            --var STRIPE_PUBLIC_KEY:"${{ vars.STRIPE_PUBLIC_KEY }}"
            --var SUPABASE_STORAGE_URL:"${{ vars.SUPABASE_STORAGE_URL }}"
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
